config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  # get 'relationship/follows' => 'relationship#follows'
  # get 'relationship/follers' => 'relationship#folloers'

  get "search" => "users#search"

  resources :books, only: [:new, :create, :index, :show, :destroy, :update, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy, :show, :index]
  resources :users, only: [:show, :edit, :update, :index]  #:ensure_correct_user
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :book_params

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_back(fallback_location: root_path)  #book_path(@book)request.referer
  end

  def book_params
    @book = Book.find(params[:book_id])
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorites.html.erb
    <!--% if book.favorited_by?(current_user) %>-->
    <!--  <p>-->
    <!--    %= link_to book_favorites_path(book), method: :delete, remote: true do %>-->
    <!--      ♥%= book.favorites.count %>-->
    <!--    % end %>-->
    <!--  </p>-->
    <!--% else %>-->
    <!--  <p>-->
    <!--    %= link_to book_favorites_path(book), method: :post, remote: true do %>-->
    <!--      ♡%= book.favorites.count %>-->
    <!--    % end %>-->
    <!--  </p>-->
    <!--% end %>-->

    <% if book.favorited_by?(current_user) %>
      <p>
        <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
          <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
          <%= book.favorites.count %>
        <% end %>
      </p>
    <% else %>
      <p>
        <%= link_to book_favorites_path(book), method: :post, remote: true do %>
          <i class="fa fa-heart-o" aria-hidden="true" style="color: red;"></i>
          <i class="fa fa-heart" aria-hidden="true" style="color: black;"></i>
          <%= book.favorites.count %>
        <% end %>
      </p>
    <% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render 'favorites/favorites', book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render 'favorites/favorites', book: @book) %>");