config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  # get 'relationship/follows' => 'relationship#follows'
  # get 'relationship/follers' => 'relationship#folloers'

  get "search" => "users#search"

  resources :books, only: [:new, :create, :index, :show, :destroy, :update, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy, :show, :index]
  resources :users, only: [:show, :edit, :update, :index]  #:ensure_correct_user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy


  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy


  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end


  def User.search(search, user_or_book, how_search)
    if user_or_book == "1"
        if how_search == "1"
            User.where(['name LIKE ?', "%#{search}%"])
        elsif how_search == "2"
            User.where(['name LIKE ?', "%#{search}"])
        elsif how_search == "3"
            User.where(['name LIKE ?', "#{search}%"])
        elsif how_search == "4"
            User.where(['name LIKE ?', "#{search}"])
        else
            User.all
        end
    end
  end


  # include JpPrefecture
  # jp_prefecture :prefecture_code,method_name: :pref

  # def prefecture_name
  #   JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  # end

  # def prefecture_name=(prefecture_name)
  #   self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  # end



  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  # validates :prefecture_name, presence: true
  # validates :address_city, presence: true
  # validates :address_street, presence: true
  # validates :address_building, presence: true

　#ユーザーのイメージ写真ID
  attachment :profile_image

end

app/controllers/users_controller.rb
class UsersController < ApplicationController #User::ApplicationController?
  before_action :ensure_correct_user,only: [:edit, :update]
  # before_action :set_user

  def show
    @new_book = Book.new
    @user = User.find(params[:id])
    # @user = User.page(books_params[:page]).reverse_order
    @books = @user.books
    @book = Book.find(params[:id])
    # @user = Kaminari.paginate_array(Book.find_all_by_book_id(params[:id])).page(params[:page]).per(5)
  end

  def index
    @book = Book.new
    @user = current_user
    @users = User.all
    # @users = User.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
    # if @user.id == current_user.id
    #   redirect_to edit_user_path(@user.id)
    # else
    #   redirect_to action: :show,id:current_user.id
    # end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user.id), notice: 'User was successfully updated.'
    else
       render :edit
    end
  end

  #binding.pry <--ターミナルの処理を止めたいところに入れる

  def search
    @user_or_book = params[:option]
    @how_search = params[:choice]
    if @user_or_book == "1"
      @users = User.search(params[:search], @user_or_book, @how_search)
    else
      @books = Book.search(params[:search], @user_or_book, @how_search)
    end
  end

  def ensure_correct_user
    @user = User.find_by(id:params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  # Mailer機能/テスト環境ではOK/本番環境では×
  # def create
  #   if @user.save
  #     NotificationMailer.send_confirm_to_user(@user).delivery
  #     redirect_to @user
  #   else
  #     render 'new'　　　　　　　　　　　＃うまくいかなかった
  #   end
  # end


  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction) #, :postcode, :prefecture_code, :address_city, :address_street, :address_building
  end

  # def user_params_update
  #   params.require(:user).permit(:name, :profile_image, :introduction)
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<!-- simple_form templete -->
<!--%= simple_form_for user do |f| %>-->

<!--  %= f.input :postcode %>-->
<!--  %= f.input :prefecture_code, collection: JpPrefecture::Prefecture.all, :value_method => :name, include_blank: '都道府県' %>-->
<!--  %= f.input :address_city %>-->
<!--  %= f.input :address_street %>-->
<!--  %= f.input :address_building %>-->
  <!--%= f.button :submit %>-->

<!--% end %>-->


<div class="field">
     <%= f.label :postcode %><br />
     <%= f.text_field :postcode, autofocus: true, autocomplete: "postcode" %>
</div>
<div class="field">
     <%= f.label :prefecture_code %><br />
     <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name, include_blank: '都道府県' %>
</div>
<div class="field">
     <%= f.label :address_city %><br />
     <%= f.text_field :address_city, autofocus: true, autocomplete: "address_city" %>
</div>
<div class="field">
     <%= f.label :address_street %><br />
     <%= f.text_field :address_street, autofocus: true, autocomplete: "address_street" %>
</div>
<div class="field">
     <%= f.label :address_building %><br />
     <%= f.text_field :address_building, autofocus: true, autocomplete: "address_building" %>
</div>

app/views/users/_search_form.html.erb
<!--%= form_tag(search_path, :method => 'get') do %>-->
<!--  %= select_tag(:option, options_for_select([["user", "1"],["book","2"]])) %>-->
<!--  %= select_tag(:choice, options_for_select([["部分一致", "1"],["後方一致", "2"],["前方一致", "3"],["完全一致", "4"]])) %>-->
<!--  %= text_field_tag :search %>-->
<!--  %= submit_tag 'Search', :name => nil %>-->
<!--% end %>-->

<%= form_with url: search_path, :method => 'get', local: true do  |f| %>
  <%= f.select(:option, options_for_select([["user", "1"],["book","2"]])) %>
  <%= f.select(:choice, options_for_select([["部分一致", "1"],["後方一致", "2"],["前方一致", "3"],["完全一致", "4"]])) %>
  <%= f.text_field :search %>
  <%= f.submit "Search", :name => nil %>
<% end %>

app/views/users/_sidebar.html.erb
    <!--<div class="row">-->
      <!--<div class="col-md-3">-->
        <h2>User info</h2>
        <p><%= attachment_image_tag user, :profile_image, size:'100x100', format: 'jpg', fallback: "no_image.jpg" %></p>
        <table class="table">
          <tbody>
            <tr>
              <th class="profile-name"> name </th>
              <th class="profile-name"> <%= user.name %> </th>
            </tr>
            <tr>
              <th class="profile-text"> introduction </th>
              <th class="profile-text"> <%= user.introduction %> </th>
            </tr>
            <tr>
              <th class="profile_text"> follows </th>
              <th>
                <%= link_to " #{user.followings.count} ", relationship_path(user.id) %>
              </th>
            </tr>
            <tr>
              <th class="profile_text"> followers </th>
              <th>
                <%= link_to " #{user.followers.count} ", relationships_path(id: user.id) %>
              </th>
            </tr>
            <tr>
              <th>
              <%= render 'relationships/follow_button', user: user %>
              </th>
            </tr>
           </tbody>
        </table>

        <!--% if user.id == current_user.id %>-->
        <%= link_to edit_user_path(user.id)  do %>
          <p class="edit-box bg-dark">
            <i class="fas fa-user-cog"></i>
          </p>
        <% end %>

app/views/users/edit.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-11 offset-md-1">
      <h2>User info</h2>

      <% if @user.errors.any? %>
      <div id="error_explanation">
        <span><%= pluralize(@user.errors.count, "error") %></span>
      </div>
      <ul id="error_explanation">
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
    </div>

    <%= form_with model:@user, local:true do |f| %>
    <div class="col-md-11 offset-md-1">
      <label for = "inputName" >Name</label>
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name" %> <!-- placeholderいる？ -->
      <!--%= attachment_image_tag @user, :profile_image, size:'40x40', fallback: "no_image.jpg"%>-->

      <label for="inputImage">ProfileImage</label>
      <%= f.attachment_field :profile_image, placeholder: "profile_image" %>
      <label for = "inputInroduction" >Introduction</label>
      <%= f.text_area :introduction, class: 'form-control', id: 'user_introduction' %> <!-- 要素不足? -->
      <%= f.submit "Update User" %>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="sidebar">
    <div class="container px-5 px-sm-0">
      <div class="row">
        <div class="col-md-3">
          <%= render 'users/sidebar', user: current_user %>

          <%= render 'books/sidebar', book: @book %>
        </div>

        <div class="col-md-8 offset-md-1">
          <h2> Users </h2>
          <table class="table">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
              <tr>
                <th>
                  <%= attachment_image_tag user, :profile_image, size:'40x40', fallback: "no_image.jpg" %>
                </th>
                <th>
                  <%= user.name %>
                </th>
                <td><%= " フォロー数: #{user.followings.count} " %></td>
                <td><%= " フォロワー数: #{user.followers.count} " %></td>
                <th>
                  <% unless current_user == user %>
                    <% if current_user.following?(user) %>
                      <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                        <%= hidden_field_tag :follow_id, user.id %>
                        <%= f.submit 'unfollow' %>
                      <% end %>
                    <% else %>
                      <%= form_for(current_user.relationships.build) do |f| %>
                        <%= hidden_field_tag :follow_id, user.id %>
                        <%= f.submit 'follow' %>
                      <% end %>
                    <% end %>
                  <% end %>
                </th>
                <th>
                  <%= link_to "Show", user_path(user.id) %>
                </th>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
</div>



<!--%= paginate @users %>-->

app/views/users/search.html.erb
<% if @user_or_book == "1" %>

  <h1>User</h1>
  <table>
    <% @users.each do |user| %>
    <thead>
      <tr>
        <th></th>
        <th><%= user.name %></th>
      </tr>
    </thead>
    <% end %>
  </table>

<% elsif @user_or_book == "2" %>

  <h2>Book</h2>
  <table>
    <% @books.each do |book| %>
    <thead>
      <tr>
        <th></th>
        <th><%= book.title %></th>
      </tr>
    </thead>
    <% end %>
  </table>

<% else %>
<% end %>

app/views/users/show.html.erb
<div class="sidebar">
    <div class="container px-5 px-sm-0">
      <div class="row">
        <div class="col-md-3">
          <%= render 'users/sidebar', user: @user %>
<!-- ここでは@modelを定義することで部分テンプレートでは@なしで記述する -->
          <%= render 'books/sidebar', book: @new_book %>
        </div>

        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th></th>
                <!--<th colspan="3"></th>-->
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user) do %>
                   <%= attachment_image_tag book.user, :profile_image, size:'40x40', fallback: "no_image.jpg" %><br>
                  <% end %>
                  <!--%= link_to users_path(current_user.id) do %>-->
                  <!--  %= book.user.name %>-->
                  <!--% end %>-->
                </td>
                <td>
                  <%= link_to book_path(book.id) do %>
                   <%= book.title %>
                  <% end %>
                </td>
                <td><%= book.body %></td>
                <td>

                  <div id="favorites_buttons_<%= book.id %>">
                    <%= render 'favorites/favorites', book: book %>
                  </div>

                </td>
                <td>
                <%= link_to " コメント数 : #{book.book_comments.count}", book_path(book.id) %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>


      </div>
    </div>
</div>



<!--%= paginate @user.books %>-->