config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  # get 'relationship/follows' => 'relationship#follows'
  # get 'relationship/follers' => 'relationship#folloers'

  get "search" => "users#search"

  resources :books, only: [:new, :create, :index, :show, :destroy, :update, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy, :show, :index]
  resources :users, only: [:show, :edit, :update, :index]  #:ensure_correct_user
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


  def Book.search(search, user_or_book, how_search)
    if user_or_book == "2"
      if how_search == "1"
        Book.where(['title LIKE ?', "%#{search}%"])
      elsif how_search == "2"
        Book.where(['title LIKE ?', "%#{search}"])
      elsif how_search == "3"
        Book.where(['title LIKE ?', "#{search}%"])
      elsif how_search == "4"
        Book.where(['title LIKE ?', "#{search}"])
      else
        Book.all
      end
    end
  end


  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  # def new
  #   @book = Book.new
  # end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       redirect_to book_path(@book), notice: 'Book was successfully created.'
    else
      # @user = current_user
      @books = Book.all
      # @book = Book.new
       render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
    # @books = Book.page(params[:page]).reverse_order
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new_book = Book.new
    @book_comment = BookComment.new
    # @book_comments = @book.comments
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    # @books = Book.all
    @book = Book.find(params[:id])
    if @book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed.'
    else
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_errors.html.erb
<% if book.errors.any? %>
<div id="error_explanation">
  <span><%= pluralize(book.errors.count, "error") %></span>
  <span>
    <%= book.errors.full_messages.each do |message| %>
      <span><%= message %></span>
  <% end %>
  </span>
</div>
<% end %>

app/views/books/_list.html.erb
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <!--<th colspan="3"></th>-->
        </tr>
      </thead>
      <tbody>
        <% books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
             <%= attachment_image_tag book.user, :profile_image, size:'40x40', fallback: "no_image.jpg" %><br>
            <% end %>
            <!--%= link_to users_path(current_user.id) do %>-->
            <!--  %= book.user.name %>-->
            <!--% end %>-->
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
             <%= book.title %>
            <% end %>
          </td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<!--%= paginate books %>-->

app/views/books/_sidebar.html.erb
  <!--<div class="row">-->
    <!--<div class="col-md-3">-->

          <p id="notice"></p>
          <%= form_with model: book, local :true do |f| %>

            <h2>New book</h2>

              <h4>Title</h4>
              <div class="book-item"><%= f.text_field :title %></div>

              <h4>Opinion</h4>
              <div class="book-item"><%= f.text_area :body %></div>

              <div class="book-box"><%= f.submit 'Create Book' %></div>

          <% end %>



    <!--</div>-->
  <!--</div>-->

app/views/books/edit.html.erb
<%= form_with model:@book, local:true do |f| %>
  <h2>Editing Book</h2>

    <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@book.errors.count, "error") %></h2>
          <ul>
              <% @book.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
          </ul>
        </div>
    <% end %>


    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %>

    <div class="box"><%= f.submit 'Update Book' %></div>

    <div class="link">
        <%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>
    </div>


<% end %>

app/views/books/index.html.erb
<%= render 'books/errors', book: @book %>

<div class="sidebar">
  <div class="container px-5 px-sm-0">
    <div class="row">

      <div class="col-md-3">
        <%= render 'users/sidebar', user: current_user %>

        <%= render 'books/sidebar', book: @book %>
      </div>

        <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                 <%= attachment_image_tag book.user, :profile_image, size:'40x40', fallback: "no_image.jpg" %><br>
                <% end %>
                <!--%= link_to users_path(current_user.id) do %>-->
                <!--  %= book.user.name %>-->
                <!--% end %>-->
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                 <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
              <td>
                <div id="favorites_buttons_<%= book.id %>">
                  <%= render 'favorites/favorites', book: book %>
                </div>
              </td>
              <td>
                <%= link_to " コメント数 : #{book.book_comments.count}", book_path(book.id) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>


    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="sidebar">
    <div class="container px-5 px-sm-0">
        <div class="row">
            <div class="col-md-3">
                <%= render 'users/sidebar', user: @book.user %>

                <%= render 'books/sidebar', book: @new_book %>
            </div>
            <div class="col-md-8 offset-md-1">
                <h2>Book detail</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Title</th>
                            <th>Opinion</th>
                            <% if @book.user == current_user %>
                            <th></th>
                            <% else %>
                            <% end %>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <%= attachment_image_tag @user, :profile_image, size:'60x60', format: 'jpg', fallback: "no_image.jpg" %><br>
                                <%= link_to user_path(@user.id) do %>
                                  <%= @book.user.name %>
                                <% end %>
                            </td>
                            <td>
                                <%= @book.title %>
                            </td>
                            <td>
                                <%= @book.body %>
                            </td>
                            <td>

                                <div id="favorites_buttons_<%= @book.id %>">
                                    <%= render 'favorites/favorites', book: @book %>
                                </div>

                            </td>
                            <td>
                                <p>コメント数 : <%= @book.book_comments.count %></p>
                            </td>
                            <% if @book.user == current_user %>
                            <td class="link1">
                                <%= link_to "Edit", edit_book_path(@book) %>
                            </td>
                            <td class="link2">
                                <%= link_to "Destroy", book_path(@book), method: :delete  %>
                            </td>
                            <% else %>
                            <% end %>
                        </tr>
                    </tbody>
                </table>
                <div>
                    <div class="comments_area">

                        <%= render 'book_comments/index', book: @book, user: @user %>

                    </div>
                    <div class="new-comment">

                        <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--<div class="container ">-->



</div>