config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  # get 'relationship/follows' => 'relationship#follows'
  # get 'relationship/follers' => 'relationship#folloers'

  get "search" => "users#search"

  resources :books, only: [:new, :create, :index, :show, :destroy, :update, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy, :show, :index]
  resources :users, only: [:show, :edit, :update, :index]  #:ensure_correct_user
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/*******.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> <!--calss="d-flex flex-column vh-100"-->
    <header> <!-- calss="shadow-sm"-->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <p class="navbar-brand">
            <%= link_to root_path do %>
            <span>Bookers</span>
            <% end %>
          </p>
          <button class="navbar-toggler" type="button" daata-toggle="collapse" data-target="#navbarNavDropdown" aria-control="navbarNavDropdown" aria-expanded="false" aria="Toggle navigation">
            <span class="navbar-toggle-icon"></span>
          </button>
          <div calss="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id) do %>
                <i class="fas fa-home text-light"> Home </i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path do %>
                <i class="fas fa-users text-light"> Users </i>    <!-- users_path? -->
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path do %>
                <i class="fas fa-book-open text-light"> Books </i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, :method => :delete do %>
                <i class="fas fa-sign-out-alt text-light"> logout </i>
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to root_path do %>
                <i class="fas fa-home text-light"> Home </i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to home_about_path do %>
                <i class="fas fa-link text-light"> About </i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path do %>
                <i class="fas fa-user-plus text-light"> Sign up </i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path do %>
                <i class="fas fa-sign-in-alt"> login </i>
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div class="container px-5 px-sm-0">
        <div class="row">
          <div class="col-md-11 offset-md-1">
            <% if user_signed_in? %>
              <%= render 'users/search_form' %>
            <% else %>
            <% end %>
          </div>
        </div>
      </div>
    </header>

    <main>
      <p id="notice"><%= notice %></p>



    <%= yield %>
      <div id="container">
        <div id="theTarget">
          <div class="image1"></div>
          <div class="image2"></div>
          <div class="image3"></div>
          <div class="image4"></div>
          <div class="image5"></div>
        </div>
      </div>
    </main>
    <footer><!-- class=" text-dark pt-5 pb-4"-->
      <div class="container mt-5">
        <div class="row"><!-- no-gutters-->
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>